/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export type LogStruct = {
  index: BigNumberish;
  timestamp: BigNumberish;
  txHash: BytesLike;
  blockNumber: BigNumberish;
  blockHash: BytesLike;
  source: string;
  topics: BytesLike[];
  data: BytesLike;
};

export type LogStructOutput = [
  BigNumber,
  BigNumber,
  string,
  BigNumber,
  string,
  string,
  string[],
  string
] & {
  index: BigNumber;
  timestamp: BigNumber;
  txHash: string;
  blockNumber: BigNumber;
  blockHash: string;
  source: string;
  topics: string[];
  data: string;
};

export interface CTMaticContractInterface extends utils.Interface {
  functions: {
    "balances(address)": FunctionFragment;
    "bytes32ToAddress(bytes32)": FunctionFragment;
    "bytes32ToUint256(bytes32)": FunctionFragment;
    "checkLog((uint256,uint256,bytes32,uint256,bytes32,address,bytes32[],bytes),bytes)": FunctionFragment;
    "convertExactMaticToToken(address)": FunctionFragment;
    "convertTokenToMatic(uint256,address)": FunctionFragment;
    "estimateMaticforToken(uint256,address)": FunctionFragment;
    "estimateTokenForMatic(uint256,address)": FunctionFragment;
    "executeTradeAndDisperce(address,uint256)": FunctionFragment;
    "performUpkeep(bytes)": FunctionFragment;
    "quoter()": FunctionFragment;
    "setSwapHelper(address)": FunctionFragment;
    "subscribe()": FunctionFragment;
    "subscriberCount()": FunctionFragment;
    "swapHelper()": FunctionFragment;
    "uniswapRouter()": FunctionFragment;
    "userBalance(address)": FunctionFragment;
    "withdraw(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "balances"
      | "bytes32ToAddress"
      | "bytes32ToUint256"
      | "checkLog"
      | "convertExactMaticToToken"
      | "convertTokenToMatic"
      | "estimateMaticforToken"
      | "estimateTokenForMatic"
      | "executeTradeAndDisperce"
      | "performUpkeep"
      | "quoter"
      | "setSwapHelper"
      | "subscribe"
      | "subscriberCount"
      | "swapHelper"
      | "uniswapRouter"
      | "userBalance"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "balances", values: [string]): string;
  encodeFunctionData(
    functionFragment: "bytes32ToAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bytes32ToUint256",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkLog",
    values: [LogStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "convertExactMaticToToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "convertTokenToMatic",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "estimateMaticforToken",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "estimateTokenForMatic",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTradeAndDisperce",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "performUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "quoter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setSwapHelper",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "subscribe", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "subscriberCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapHelper",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapRouter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "userBalance", values: [string]): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bytes32ToAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bytes32ToUint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "checkLog", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "convertExactMaticToToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertTokenToMatic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimateMaticforToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimateTokenForMatic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTradeAndDisperce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "performUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "quoter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSwapHelper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subscriberCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapHelper", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "uniswapRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "BuyOrder(address,uint256,address)": EventFragment;
    "SellOrder(address,uint256,address)": EventFragment;
    "logDisperce(uint256,uint256,uint256,uint8,address[])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BuyOrder"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SellOrder"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "logDisperce"): EventFragment;
}

export interface BuyOrderEventObject {
  tokenContractAddress: string;
  amount: BigNumber;
  recipient: string;
}
export type BuyOrderEvent = TypedEvent<
  [string, BigNumber, string],
  BuyOrderEventObject
>;

export type BuyOrderEventFilter = TypedEventFilter<BuyOrderEvent>;

export interface SellOrderEventObject {
  tokenContractAddress: string;
  amount: BigNumber;
  recipient: string;
}
export type SellOrderEvent = TypedEvent<
  [string, BigNumber, string],
  SellOrderEventObject
>;

export type SellOrderEventFilter = TypedEventFilter<SellOrderEvent>;

export interface logDisperceEventObject {
  swapAmount: BigNumber;
  receivedTokens: BigNumber;
  tokensToDistributePerUser: BigNumber;
  fundedSubscriberCount: number;
  fundedSubscribers: string[];
}
export type logDisperceEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, number, string[]],
  logDisperceEventObject
>;

export type logDisperceEventFilter = TypedEventFilter<logDisperceEvent>;

export interface CTMaticContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CTMaticContractInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    balances(
      subscriber: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { balance: BigNumber }>;

    bytes32ToAddress(
      _address: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    bytes32ToUint256(
      _amount: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    checkLog(
      log: LogStruct,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [boolean, string] & { upkeepNeeded: boolean; performData: string }
    >;

    convertExactMaticToToken(
      _tokenOut: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    convertTokenToMatic(
      amountIn: BigNumberish,
      token: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    estimateMaticforToken(
      tokenAmountOut: BigNumberish,
      token: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    estimateTokenForMatic(
      MaticAmount: BigNumberish,
      token: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    executeTradeAndDisperce(
      tokenContractAddress: string,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    performUpkeep(
      performData: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    quoter(overrides?: CallOverrides): Promise<[string]>;

    setSwapHelper(
      _swapHelper: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    subscribe(
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    subscriberCount(overrides?: CallOverrides): Promise<[number]>;

    swapHelper(overrides?: CallOverrides): Promise<[string]>;

    uniswapRouter(overrides?: CallOverrides): Promise<[string]>;

    userBalance(user: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    withdraw(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  balances(subscriber: string, overrides?: CallOverrides): Promise<BigNumber>;

  bytes32ToAddress(
    _address: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  bytes32ToUint256(
    _amount: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  checkLog(
    log: LogStruct,
    arg1: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [boolean, string] & { upkeepNeeded: boolean; performData: string }
  >;

  convertExactMaticToToken(
    _tokenOut: string,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  convertTokenToMatic(
    amountIn: BigNumberish,
    token: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  estimateMaticforToken(
    tokenAmountOut: BigNumberish,
    token: string,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  estimateTokenForMatic(
    MaticAmount: BigNumberish,
    token: string,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  executeTradeAndDisperce(
    tokenContractAddress: string,
    amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  performUpkeep(
    performData: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  quoter(overrides?: CallOverrides): Promise<string>;

  setSwapHelper(
    _swapHelper: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  subscribe(
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  subscriberCount(overrides?: CallOverrides): Promise<number>;

  swapHelper(overrides?: CallOverrides): Promise<string>;

  uniswapRouter(overrides?: CallOverrides): Promise<string>;

  userBalance(user: string, overrides?: CallOverrides): Promise<BigNumber>;

  withdraw(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    balances(subscriber: string, overrides?: CallOverrides): Promise<BigNumber>;

    bytes32ToAddress(
      _address: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    bytes32ToUint256(
      _amount: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkLog(
      log: LogStruct,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [boolean, string] & { upkeepNeeded: boolean; performData: string }
    >;

    convertExactMaticToToken(
      _tokenOut: string,
      overrides?: CallOverrides
    ): Promise<void>;

    convertTokenToMatic(
      amountIn: BigNumberish,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    estimateMaticforToken(
      tokenAmountOut: BigNumberish,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    estimateTokenForMatic(
      MaticAmount: BigNumberish,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    executeTradeAndDisperce(
      tokenContractAddress: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    performUpkeep(
      performData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    quoter(overrides?: CallOverrides): Promise<string>;

    setSwapHelper(
      _swapHelper: string,
      overrides?: CallOverrides
    ): Promise<void>;

    subscribe(overrides?: CallOverrides): Promise<void>;

    subscriberCount(overrides?: CallOverrides): Promise<number>;

    swapHelper(overrides?: CallOverrides): Promise<string>;

    uniswapRouter(overrides?: CallOverrides): Promise<string>;

    userBalance(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(amount: BigNumberish, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "BuyOrder(address,uint256,address)"(
      tokenContractAddress?: string | null,
      amount?: BigNumberish | null,
      recipient?: null
    ): BuyOrderEventFilter;
    BuyOrder(
      tokenContractAddress?: string | null,
      amount?: BigNumberish | null,
      recipient?: null
    ): BuyOrderEventFilter;

    "SellOrder(address,uint256,address)"(
      tokenContractAddress?: string | null,
      amount?: BigNumberish | null,
      recipient?: null
    ): SellOrderEventFilter;
    SellOrder(
      tokenContractAddress?: string | null,
      amount?: BigNumberish | null,
      recipient?: null
    ): SellOrderEventFilter;

    "logDisperce(uint256,uint256,uint256,uint8,address[])"(
      swapAmount?: null,
      receivedTokens?: null,
      tokensToDistributePerUser?: null,
      fundedSubscriberCount?: null,
      fundedSubscribers?: null
    ): logDisperceEventFilter;
    logDisperce(
      swapAmount?: null,
      receivedTokens?: null,
      tokensToDistributePerUser?: null,
      fundedSubscriberCount?: null,
      fundedSubscribers?: null
    ): logDisperceEventFilter;
  };

  estimateGas: {
    balances(subscriber: string, overrides?: CallOverrides): Promise<BigNumber>;

    bytes32ToAddress(
      _address: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bytes32ToUint256(
      _amount: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkLog(
      log: LogStruct,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertExactMaticToToken(
      _tokenOut: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    convertTokenToMatic(
      amountIn: BigNumberish,
      token: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    estimateMaticforToken(
      tokenAmountOut: BigNumberish,
      token: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    estimateTokenForMatic(
      MaticAmount: BigNumberish,
      token: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    executeTradeAndDisperce(
      tokenContractAddress: string,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    performUpkeep(
      performData: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    quoter(overrides?: CallOverrides): Promise<BigNumber>;

    setSwapHelper(
      _swapHelper: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    subscribe(
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    subscriberCount(overrides?: CallOverrides): Promise<BigNumber>;

    swapHelper(overrides?: CallOverrides): Promise<BigNumber>;

    uniswapRouter(overrides?: CallOverrides): Promise<BigNumber>;

    userBalance(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    balances(
      subscriber: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bytes32ToAddress(
      _address: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bytes32ToUint256(
      _amount: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkLog(
      log: LogStruct,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertExactMaticToToken(
      _tokenOut: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    convertTokenToMatic(
      amountIn: BigNumberish,
      token: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    estimateMaticforToken(
      tokenAmountOut: BigNumberish,
      token: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    estimateTokenForMatic(
      MaticAmount: BigNumberish,
      token: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    executeTradeAndDisperce(
      tokenContractAddress: string,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    performUpkeep(
      performData: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    quoter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setSwapHelper(
      _swapHelper: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    subscribe(
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    subscriberCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swapHelper(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    uniswapRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    userBalance(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
